phr(G,N,T)-->subj(G,N),pred(T,N).
pred(T,N)-->v(T,N),objd(G,M).
pred(T,N)-->v(T,N),sadj(G,M).
pred(T,N)-->vti(T,N),sprep(G,M).
objd(G,N)-->n(G,N).
objd(G,N)-->det(G,N),n(G,N).
subj(G,N)-->n(G,N).
subj(G,N)-->det(G,N),n(G,N).
sadj(G,N)-->subj(G,N),adj(G,N).
sprep(G,N)-->prep(G,N),obji(G,N).
n(f,s)-->[nana].
n(f,s)-->[gata].
n(m,s)-->[gato].
n(m,s)-->[zoinho].
n(m,p)-->[tucanos].
obji(f,s)-->[ufscar].
det(f,s)-->[a].
det(m,s)-->[o].
det(m,p)-->[os].
det(f,s)-->[uma].
det(m,s)-->[um].
adj(m,s)-->[pequeno].
v(pre,s)-->[é].
v(pas,s)-->[era].
vti(pre,p)-->[voam].
prep(f,s)-->[na].
