phr(phr(SUBJ,PRED,G,N,T))-->subj(SUBJ),pred(PRED).
pred(pred(VCOP,OBJ,G,T,N))-->vcop(VCOP,T,N),obj(OBJ).
pred(pred(VT,OBJ,G,T,N))-->vt(VT,T,N),obj(OBJ).
pred(pred(VT,SADJ,G,T,N))-->vt(VT,T,N),sadj(SADJ).
pred(pred(VTI,SPREP,G,T,N))-->vti(VTI,T,N),sprep(SPREP).
obj(obj(NPROP,G,N))-->nprop(NPROP,G,N).
obj(obj(N,G,N))-->n(N,G,N).
obj(obj(DET,NPROP,G,N))-->det(DET,G,N),nprop(NPROP,G,N).
obj(obj(DET,N,G,N))-->det(DET,G,N),n(N,G,N).
subj(subj(NPROP,G,N))-->nprop(NPROP,G,N).
subj(subj(DET,NPROP,G,N))-->det(DET,G,N),nprop(NPROP,G,N).
subj(subj(DET,N,G,N))-->det(DET,G,N),n(N,G,N).
sadj(sadj(SUBJ,ADJ,G,N))-->subj(SUBJ),adj(ADJ,G,N).
sprep(sprep(PREP,OBJI,G,N))-->prep(PREP,G,N),obji(OBJI,G,N).
nprop(nprop(nana),f,s)-->[nana].
nprop(nprop(zoinho),m,s)-->[zoinho].
n(n(gata),f,s)-->[gata].
n(n(gato),m,s)-->[gato].
n(n(tucanos),m,p)-->[tucanos].
obji(obji(ufscar),f,s)-->[ufscar].
det(det(a),f,s)-->[a].
det(det(o),m,s)-->[o].
det(det(os),m,p)-->[os].
det(det(uma),f,s)-->[uma].
det(det(um),m,s)-->[um].
adj(adj(pequeno),m,s)-->[pequeno].
vcop(vcop(é),pre,s)-->[é].
vcop(vcop(era),pas,s)-->[era].
vt(vt(comeu),pas,s)-->[comeu].
vti(vti(voam),pre,p)-->[voam].
prep(prep(na),f,s)-->[na].
